export const add = 'http://oss.suning.com/sffe/sffe/add.png'
export const arrowRight = 'http://oss.suning.com/sffe/sffe/arrowRight202104201601.png'
export const bottomBg = 'http://oss.suning.com/sffe/sffe/bottomBg.png'
export const backBlack = 'http://oss.suning.com/sffe/sffe/backBlack.png'
export const backWhite = 'http://oss.suning.com/sffe/sffe/backWhite.png'
export const goods = 'http://oss.suning.com/sffe/sffe/goods.png'
export const fire = 'http://oss.suning.com/sffe/sffe/fire.png'
export const one = 'http://oss.suning.com/sffe/sffe/oneIcon.png'
export const order = 'http://oss.suning.com/sffe/sffe/order.png'
export const shopCart = 'http://oss.suning.com/sffe/sffe/shopCart.png'
export const discount = 'http://oss.suning.com/sffe/sffe/discount.png'
export const second = 'http://oss.suning.com/sffe/sffe/twoIcon.png'
export const third = 'http://oss.suning.com/sffe/sffe/threeIcon.png'
export const left = 'http://oss.suning.com/sffe/sffe/left.png'

export const subtract_disabled = 'http://oss.suning.com/sffe/sffe/stepper_subtract_disabled.png'
export const subtract_active = 'http://oss.suning.com/sffe/sffe/stepper_subtract_active.png'
export const single_add = 'http://oss.suning.com/sffe/sffe/single_add.png'
export const add_disabled = 'http://oss.suning.com/sffe/sffe/stepper_add_disabled.png'
export const add_active = 'http://oss.suning.com/sffe/sffe/stepper_add_active.png'

export const default_goods_img = 'http://oss.suning.com/sffe/sffe/default_goods.png'

export const banner = 'http://oss.suning.com/sffe/sffe/banner20210610.png'
export const titleBg = 'http://oss.suning.com/sffe/sffe/title20210610.png'

export const coupon_card_red = 'https://oss.suning.com/sffe/sffe/coupon_card_red.png'
export const coupon_card_yellow = 'https://oss.suning.com/sffe/sffe/coupon_card_yellow.png'
export const coupon_overdue_icon_expired_black = 'https://oss.suning.com/sffe/sffe/coupon_overdue_icon_black.png'
export const coupon_overdue_icon_used_grey = 'https://oss.suning.com/sffe/sffe/coupon_overdue_icon_grey.png'
export const coupon_icon_finish_received = 'https://oss.suning.com/sffe/sffe/coupon_icon_finish_received.png'
export const coupon_icon_un_begin = 'https://oss.suning.com/sffe/sffe/coupon_icon_un_begin.png'
export const coupon_card_content = 'https://oss.suning.com/sffe/sffe/coupon_card_content.png'
export const coupon_card_content_grey = 'https://oss.suning.com/sffe/sffe/coupon_card_content_grey20210707.png'
export const coupon_card_grey = 'https://oss.suning.com/sffe/sffe/coupon_card_grey.png'
export const coupon_top_banner = 'https://oss.suning.com/sffe/sffe/coupon_new_top_banner.png'

export const couponRed = 'http://oss.suning.com/sffe/sffe/coupon-red.png'
export const couponYellow = 'http://oss.suning.com/sffe/sffe/coupon-yellow.png'
export const sorterDefault = 'http://oss.suning.com/sffe/sffe/sorter-default.png'
export const sorterDown = 'http://oss.suning.com/sffe/sffe/sorter-down.png'
export const sorterUp = 'http://oss.suning.com/sffe/sffe/sorter-up.png'

export const customer_promotion_bg = 'https://oss.suning.com/sffe/sffe/customer_promotion.png'
export const customer_promotion_qrcode_icon = 'https://oss.suning.com/sffe/sffe/customer_promotion_qrcode_icon2021.png'
export const customer_promotion_myCustomer_icon =
  'https://oss.suning.com/sffe/sffe/customer_promotion_myCustomer_icon.png'
export const customer_promotion_benfit_icon = 'https://oss.suning.com/sffe/sffe/customer_promotion_benfit_icon.png'

export const info_black_icon = 'https://oss.suning.com/sffe/sffe/info_black_icon.png'
export const info_white_icon = 'https://oss.suning.com/sffe/sffe/info-white@3.png'

export const close_icon = 'https://oss.suning.com/sffe/sffe/close20210804.png'
export const no_data = 'https://oss.suning.com/sffe/sffe/pager_lion.png'
export const carrefour_logo = 'https://oss.suning.com/sffe/sffe/carrefour_logo.png'

export const clock = 'https://oss.suning.com/sffe/sffe/clock@3x.png'
export const close = 'https://oss.suning.com/sffe/sffe/close@3x.png'
export const arrowDown = 'https://oss.suning.com/sffe/sffe/down@3x.png'
export const arrowUp = 'https://oss.suning.com/sffe/sffe/up@3x.png'
export const more = 'https://oss.suning.com/sffe/sffe/more@3x.png'
